[project]
name = "kaseb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "asyncio>=4.0.0",
    "motor>=3.7.1",
    "pymongo>=4.14.1",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "rnet>=2.4.2",
]
